---
title: "ECO 395 Homework 3: Taylor Neal"
output: rmarkdown::github_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
library(tidyverse)
library(knitr)
#library(rsample)
#library(caret)
#library(modelr)
#library(glmnet)
#library(lubridate)
#library(ROCR)
#library(foreach)
#library(mosaic)


dengue <- read.csv("https://raw.githubusercontent.com/taylorneal/homework-3/master/data/dengue.csv", header = TRUE)
grn_build <- read.csv("https://raw.githubusercontent.com/taylorneal/homework-3/master/data/greenbuildings.csv", header = TRUE)
CA_housing <- read.csv("https://raw.githubusercontent.com/taylorneal/homework-3/master/data/CAhousing.csv", header = TRUE)

set.seed(9)
```
## 1) What Causes What?

##### Why can’t I just get data from a few different cities and run the regression of “Crime” on “Police” to understand how more cops in the streets affect crime? (“Crime” refers to some measure of crime rate and “Police” measures the number of cops in a city.)

TBU

##### How were the researchers from UPenn able to isolate this effect? Briefly describe their approach and discuss their result in the “Table 2” below, from the researchers' paper.

TBU

##### Why did they have to control for Metro ridership? What was that trying to capture?

TBU

##### Below I am showing you "Table 4" from the researchers' paper. Just focus on the first column of the table. Can you describe the model being estimated here? What is the conclusion?

TBU

## 2) Tree Modeling: Dengue Cases

TBU

## 3) Predictive Model Building: Green Certification

TBU 

## 4) Predictive Model Building: California Housing

TBU